<?php
/**
 * SHM PANEL - WEB INSTALLER (Updated with Security Tables)
 * =========================
 * Single-file setup wizard to fix database connections and initialize the system.
 * 
 * UPDATED: Now includes security tables for the new security implementation
 */

// Disable error display for production
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Define installer constant to bypass redirect loops in config
define('INSTALLER_RUNNING', true);

$error = '';
$success = '';
$step = 1;

// Check if system is already installed
$config_file = __DIR__ . '/shared/config.local.php';
$installed = false;

if (file_exists($config_file)) {
    try {
        require_once $config_file;
        // Test connection
        $test_pdo = new PDO("mysql:host=$db_host;dbname=$db_name;charset=utf8mb4", $db_user, $db_pass);
        $test_pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        // Check if admins table exists
        $stmt = $test_pdo->query("SELECT COUNT(*) FROM admins");
        if ($stmt && $stmt->fetchColumn() > 0) {
            $installed = true;
        }
    } catch (Exception $e) {
        // Config exists but connection failed - allow reinstall
        $installed = false;
    }
}

// Handle Form Submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$installed) {
    $db_host = $_POST['db_host'] ?? 'localhost';
    $db_name = $_POST['db_name'] ?? 'shm_panel';
    $db_user = $_POST['db_user'] ?? 'root';
    $db_pass = $_POST['db_pass'] ?? '';
    $admin_user = $_POST['admin_user'] ?? 'admin';
    $admin_pass = $_POST['admin_pass'] ?? 'admin123';

    // Validate inputs
    if (empty($db_host) || empty($db_name) || empty($db_user)) {
        $error = "Database host, name, and user are required!";
    } elseif (strlen($admin_pass) < 6) {
        $error = "Admin password must be at least 6 characters!";
    } else {
        try {
            // 1. Test Connection
            $pdo = new PDO("mysql:host=$db_host;charset=utf8mb4", $db_user, $db_pass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

            // 2. Create Database
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `$db_name`");

            // 3. Write Config File (Ensure directory exists)
            $shared_dir = __DIR__ . '/shared';
            if (!is_dir($shared_dir)) {
                mkdir($shared_dir, 0755, true);
            }

            $config_content = "<?php\n";
            $config_content .= "// Local Configuration generated by Installer\n";
            $config_content .= "// Date: " . date('Y-m-d H:i:s') . "\n\n";
            $config_content .= "\$db_host = '" . addslashes($db_host) . "';\n";
            $config_content .= "\$db_name = '" . addslashes($db_name) . "';\n";
            $config_content .= "\$db_user = '" . addslashes($db_user) . "';\n";
            $config_content .= "\$db_pass = '" . addslashes($db_pass) . "';\n\n";
            $config_content .= "// Main domain for system\n";
            $config_content .= "\$MAIN_DOMAIN = \$_SERVER['HTTP_HOST'] ?? 'localhost';\n";
            $config_content .= "\$ADMIN_EMAIL = 'admin@' . \$MAIN_DOMAIN;\n\n";
            $config_content .= "// Ensure no output before headers\n";
            $config_content .= "ob_start();\n";
            $config_content .= "?>";

            if (file_put_contents($config_file, $config_content) === false) {
                throw new Exception("Cannot write config file. Check directory permissions.");
            }

            // 4. Import Schema from unified schema.sql
            $schema_file = __DIR__ . '/installer/schema.sql';
            if (!file_exists($schema_file)) {
                throw new Exception("Cannot find installer/schema.sql to initialize database.");
            }
            $schema_sql = file_get_contents($schema_file);
            try {
                // PDO can execute multiple queries in a single string if emulate prepares is on,
                // but for robust parsing across drivers, it's safer to just execute the block.
                $pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, true);
                $pdo->exec($schema_sql);
            } catch (PDOException $e) {
                throw new Exception("Error importing unified schema: " . $e->getMessage());
            }

            // 5. Create Admin User
            $hash = password_hash($admin_pass, PASSWORD_BCRYPT);
            $stmt = $pdo->prepare("
                INSERT INTO admins (username, password, email, role) 
                VALUES (?, ?, ?, 'superadmin') 
                ON DUPLICATE KEY UPDATE password = ?, role = 'superadmin'
            ");
            $admin_email = $admin_user . '@' . ($_SERVER['HTTP_HOST'] ?? 'localhost');
            $stmt->execute([$admin_user, $hash, $admin_email, $hash]);

            // 6. Insert initial security log entry
            $stmt = $pdo->prepare("
                INSERT INTO security_logs (event, severity, ip, user, user_agent, context) 
                VALUES (?, 'info', ?, 'installer', ?, ?)
            ");
            $stmt->execute([
                'System installed successfully',
                $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1',
                $_SERVER['HTTP_USER_AGENT'] ?? 'Installer',
                json_encode(['version' => '1.0.0', 'timestamp' => date('Y-m-d H:i:s')])
            ]);

            // 7. Create necessary directories
            $directories = [
                '/var/log',
                '/var/www/clients',
                '/etc/bind/zones',
                '/shared/templates',
                '/shared/backups'
            ];

            // Create symbolic links to shared directory if needed
            if (!file_exists(__DIR__ . '/shared')) {
                mkdir(__DIR__ . '/shared', 0755, true);
            }

            $success = "Installation successful! Security features enabled. You can now access the panel.";
            $step = 2; // Show success step

            // Set installed flag
            $installed = true;

        } catch (PDOException $e) {
            $error = "Database Error: " . $e->getMessage() . " (Code: " . $e->getCode() . ")";
        } catch (Exception $e) {
            $error = "System Error: " . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Install SHM Panel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;800&display=swap"
        rel="stylesheet">
    <style>
        body {
            font-family: 'Plus Jakarta Sans', sans-serif;
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
            color: #fff;
            min-height: 100vh;
        }

        .glass {
            background: rgba(15, 23, 42, 0.8);
            backdrop-filter: blur(20px);
            border: 1px solid rgba(255, 255, 255, 0.1);
        }

        .progress-bar {
            height: 4px;
            background: rgba(255, 255, 255, 0.1);
            border-radius: 2px;
            overflow: hidden;
        }

        .progress-fill {
            height: 100%;
            background: linear-gradient(90deg, #3b82f6 0%, #8b5cf6 100%);
            transition: width 0.5s ease;
        }
    </style>
</head>

<body class="flex items-center justify-center p-4">

    <div class="w-full max-w-2xl">
        <!-- Header -->
        <div class="text-center mb-8">
            <h1
                class="text-5xl font-black bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent mb-3">
                SHM PANEL
            </h1>
            <p class="text-slate-400 text-lg">Web Hosting Control Panel - Installation Wizard</p>
            <p class="text-slate-500 text-sm mt-2">✨ Now with Enhanced Security Features</p>
        </div>

        <!-- Progress Bar -->
        <div class="progress-bar mb-8">
            <div class="progress-fill" style="width: <?= $installed ? '100' : '50' ?>%;"></div>
        </div>

        <!-- Main Card -->
        <div class="glass rounded-2xl p-8 shadow-2xl">

            <?php if ($error): ?>
                <div class="bg-red-500/10 border border-red-500/30 text-red-400 px-6 py-4 rounded-xl mb-6 backdrop-blur">
                    <div class="flex items-start">
                        <span class="text-2xl mr-3">❌</span>
                        <div>
                            <p class="font-bold mb-1">Installation Error</p>
                            <p class="text-sm opacity-90"><?= htmlspecialchars($error) ?></p>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($installed): ?>
                <!-- Success Screen -->
                <div class="text-center py-8">
                    <div class="text-7xl mb-6">🎉</div>
                    <h2 class="text-3xl font-bold mb-4">Installation Complete!</h2>
                    <p class="text-slate-400 mb-8">
                        <?= $success ? htmlspecialchars($success) : 'Your SHM Panel is ready to use with enhanced security features.' ?>
                    </p>

                    <div class="bg-slate-800/50 rounded-xl p-6 mb-6 text-left">
                        <h3 class="font-bold text-lg mb-4 text-blue-400">🔒 Security Features Enabled:</h3>
                        <ul class="space-y-2 text-sm text-slate-300">
                            <li>✅ SQL Injection Protection (Prepared Statements)</li>
                            <li>✅ CSRF Token Validation</li>
                            <li>✅ Secure Session Management</li>
                            <li>✅ Security Event Logging</li>
                            <li>✅ Login Attempt Tracking</li>
                            <li>✅ Error Logging System</li>
                        </ul>
                    </div>

                    <div class="bg-blue-500/10 border border-blue-500/30 rounded-xl p-6 mb-6">
                        <h3 class="font-bold mb-3 text-blue-400">📋 Next Steps:</h3>
                        <ol class="text-left text-sm text-slate-300 space-y-3">
                            <li class="flex items-start">
                                <span class="font-bold mr-2">1.</span>
                                <div>
                                    <strong>Apply Database Schema Fixes</strong><br>
                                    <code class="bg-slate-900 px-2 py-1 rounded text-xs">
                                                    mysql -u root -p shm_panel < migrations/003_fix_all_schema_issues.sql
                                                </code>
                                </div>
                            </li>
                            <li class="flex items-start">
                                <span class="font-bold mr-2">2.</span>
                                <div>
                                    <strong>Configure DNS Records</strong><br>
                                    Add A records for: whm.vivzon.cloud, cpanel.vivzon.cloud, phpmyadmin.vivzon.cloud,
                                    webmail.vivzon.cloud
                                </div>
                            </li>
                            <li class="flex items-start">
                                <span class="font-bold mr-2">3.</span>
                                <div>
                                    <strong>Setup Subdomains</strong><br>
                                    <code class="bg-slate-900 px-2 py-1 rounded text-xs">
                                                    chmod +x setup_subdomains.sh && ./setup_subdomains.sh
                                                </code>
                                </div>
                            </li>
                            <li class="flex items-start">
                                <span class="font-bold mr-2">4.</span>
                                <div>
                                    <strong>Secure Installation</strong><br>
                                    Delete <code class="bg-slate-900 px-2 py-1 rounded">install.php</code> and remove test
                                    files
                                </div>
                            </li>
                            <li class="flex items-start">
                                <span class="font-bold mr-2">5.</span>
                                <div>
                                    <strong>Read Complete Guide</strong><br>
                                    See <code class="bg-slate-900 px-2 py-1 rounded">README.md</code> for detailed
                                    instructions
                                </div>
                            </li>
                        </ol>
                    </div>

                    <div class="bg-yellow-500/10 border border-yellow-500/30 rounded-xl p-4 mb-6 text-left">
                        <p class="text-xs text-yellow-300">
                            <strong>⚠️ Important:</strong> The panel is now accessible but requires subdomain configuration
                            for production use. Follow the complete guide in README.md for best results.
                        </p>
                    </div>

                    <div class="flex gap-4">
                        <a href="/whm/"
                            class="flex-1 bg-gradient-to-r from-purple-600 to-purple-500 text-white font-bold py-4 rounded-xl hover:scale-[1.02] transition transform text-center">
                            Admin Panel
                        </a>
                        <a href="/cpanel/"
                            class="flex-1 bg-gradient-to-r from-blue-600 to-blue-500 text-white font-bold py-4 rounded-xl hover:scale-[1.02] transition transform text-center">
                            Client Panel
                        </a>
                    </div>
                </div>

            <?php else: ?>
                <!-- Installation Form -->
                <h2 class="text-2xl font-bold mb-6">Database & Admin Setup</h2>

                <form method="POST" class="space-y-6">
                    <!-- Database Configuration -->
                    <div class="space-y-4">
                        <h3 class="text-lg font-bold text-slate-300">Database Configuration</h3>

                        <div>
                            <label class="block text-xs font-bold uppercase text-slate-500 mb-2 ml-1">Database Host</label>
                            <input name="db_host" value="localhost" required
                                class="w-full bg-slate-900/50 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-blue-500 transition text-sm placeholder-slate-500"
                                placeholder="Usually 'localhost'">
                        </div>

                        <div>
                            <label class="block text-xs font-bold uppercase text-slate-500 mb-2 ml-1">Database Name</label>
                            <input name="db_name" value="shm_panel" required
                                class="w-full bg-slate-900/50 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-blue-500 transition text-sm placeholder-slate-500"
                                placeholder="Database name to create">
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label class="block text-xs font-bold uppercase text-slate-500 mb-2 ml-1">Database
                                    Username</label>
                                <input name="db_user" value="root" required
                                    class="w-full bg-slate-900/50 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-blue-500 transition text-sm placeholder-slate-500"
                                    placeholder="MySQL username">
                            </div>
                            <div>
                                <label class="block text-xs font-bold uppercase text-slate-500 mb-2 ml-1">Database
                                    Password</label>
                                <input name="db_pass" type="password"
                                    class="w-full bg-slate-900/50 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-blue-500 transition text-sm placeholder-slate-500"
                                    placeholder="MySQL password">
                            </div>
                        </div>
                    </div>

                    <div class="h-px bg-white/5 my-4"></div>

                    <!-- Admin Account -->
                    <div class="space-y-4">
                        <h3 class="text-lg font-bold text-slate-300">Admin Account</h3>

                        <div>
                            <label class="block text-xs font-bold uppercase text-slate-500 mb-2 ml-1">Admin Username</label>
                            <input name="admin_user" value="admin" required
                                class="w-full bg-slate-900/50 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-blue-500 transition text-sm placeholder-slate-500"
                                placeholder="Admin panel username">
                        </div>

                        <div>
                            <label class="block text-xs font-bold uppercase text-slate-500 mb-2 ml-1">Admin Password</label>
                            <input name="admin_pass" type="password" value="admin123" required
                                class="w-full bg-slate-900/50 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-blue-500 transition text-sm placeholder-slate-500"
                                placeholder="Minimum 6 characters">
                            <p class="text-xs text-slate-500 mt-2 ml-1">Choose a strong password for admin access</p>
                        </div>
                    </div>

                    <!-- Prerequisites Check -->
                    <div class="bg-slate-800/30 p-4 rounded-xl border border-slate-700">
                        <h4 class="font-bold text-sm text-slate-300 mb-3">System Requirements</h4>
                        <div class="space-y-2 text-sm">
                            <?php
                            $checks = [
                                'PHP Version (>= 7.4)' => version_compare(PHP_VERSION, '7.4.0', '>='),
                                'PDO MySQL Extension' => extension_loaded('pdo_mysql'),
                                'JSON Extension' => extension_loaded('json'),
                                'OpenSSL Extension' => extension_loaded('openssl'),
                                'File Uploads Enabled' => ini_get('file_uploads'),
                                'Config Directory Writable' => is_writable(__DIR__ . '/shared') || is_writable(__DIR__),
                            ];

                            foreach ($checks as $label => $status) {
                                echo '<div class="flex items-center">';
                                echo $status ? '✅' : '❌';
                                echo '<span class="ml-2 ' . ($status ? 'text-emerald-400' : 'text-red-400') . '">' . $label . '</span>';
                                echo '</div>';
                            }
                            ?>
                        </div>
                    </div>

                    <button type="submit"
                        class="w-full bg-gradient-to-r from-blue-600 to-blue-500 text-white font-bold py-4 rounded-xl shadow-lg shadow-blue-600/20 hover:scale-[1.02] transition transform mt-2">
                        Install SHM Panel with Security Features
                    </button>

                    <div class="text-center text-xs text-slate-500 mt-4">
                        This will create the database, tables (including security tables), and initial admin account.
                    </div>
                </form>
            <?php endif; ?>
        </div>
    </div>

    <!-- Script for form validation -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const form = document.querySelector('form');
            if (form) {
                form.addEventListener('submit', function (e) {
                    const password = document.querySelector('input[name="admin_pass"]');
                    if (password && password.value.length < 6) {
                        e.preventDefault();
                        alert('Admin password must be at least 6 characters long.');
                        password.focus();
                    }
                });
            }
        });
    </script>
</body>

</html>