#!/bin/bash

# ==============================================================================
# SHM PANEL - CONFIGURATION
# ==============================================================================

CONFIG_FILE="$(dirname "${BASH_SOURCE[0]}")/config.env"

# Load or Generate Configuration
load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
        log "Loaded configuration from $CONFIG_FILE"
    else
        log "Configuration file not found. Starting interactive setup..."
        generate_config
    fi
}

# Interactive Configuration Generator
generate_config() {
    echo -e "${CYAN}===============================================${NC}"
    echo -e "${CYAN}           CONFIGURATION WIZARD${NC}"
    echo -e "${CYAN}===============================================${NC}"
    
    # 1. Main Domain
    read -p "Enter Main Domain (e.g. example.com): " INPUT_DOMAIN
    while [[ ! "$INPUT_DOMAIN" =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; do
        echo -e "${RED}Invalid domain format. Try again.${NC}"
        read -p "Enter Main Domain (e.g. example.com): " INPUT_DOMAIN
    done
    export MAIN_DOMAIN="$INPUT_DOMAIN"
    
    # 2. Admin Email
    read -p "Enter Admin Email (e.g. admin@$MAIN_DOMAIN): " INPUT_EMAIL
    if [ -z "$INPUT_EMAIL" ]; then
        INPUT_EMAIL="admin@$MAIN_DOMAIN"
    fi
    while [[ ! "$INPUT_EMAIL" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; do
        echo -e "${RED}Invalid email format. Try again.${NC}"
        read -p "Enter Admin Email: " INPUT_EMAIL
    done
    export ADMIN_EMAIL="$INPUT_EMAIL"
    
    # 3. Server IP
    SERVER_IP=$(hostname -I | awk '{print $1}')
    read -p "Enter Server IP [$SERVER_IP]: " INPUT_IP
    if [ -n "$INPUT_IP" ]; then
        SERVER_IP="$INPUT_IP"
    fi
    export SERVER_IP
    
    # 4. Database Credentials (Auto-generated by default)
    export DB_NAME="shm_panel"
    export DB_USER="shm_admin"
    export DB_PASS=$(openssl rand -base64 16)
    export MYSQL_ROOT_PASS=$(openssl rand -base64 18)
    export ADMIN_PASS=$(openssl rand -base64 12)
    
    # Save to config.env
    cat > "$CONFIG_FILE" << EOF
# SHM Panel Configuration
# Generated on $(date)

MAIN_DOMAIN="$MAIN_DOMAIN"
ADMIN_EMAIL="$ADMIN_EMAIL"
SERVER_IP="$SERVER_IP"

# Database Configuration
DB_NAME="$DB_NAME"
DB_USER="$DB_USER"
DB_PASS="$DB_PASS"
MYSQL_ROOT_PASS="$MYSQL_ROOT_PASS"

# Admin Credentials
ADMIN_PASS="$ADMIN_PASS"
EOF
    
    chmod 600 "$CONFIG_FILE"
    log "Configuration saved to $CONFIG_FILE"
    
    # Summary
    echo -e "${CYAN}===============================================${NC}"
    echo -e "${CYAN}           INSTALLATION SUMMARY${NC}"
    echo -e "${CYAN}===============================================${NC}"
    echo "Target Domain:    $MAIN_DOMAIN"
    echo "Server IP:        $SERVER_IP"
    echo "Admin Email:      $ADMIN_EMAIL"
    echo "Database Name:    $DB_NAME"
    echo -e "${CYAN}===============================================${NC}"
    
    read -p "Proceed with installation? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
}
